---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.1 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.10.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.1 enthält mehrere neue Funktionen und Verbesserungen.

Zusätzliche Funktionen und Erweiterungen sind ebenfalls in den neuesten Versionen von BlueXP verfügbar. Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Entsprechende Details.



== 9.10.1 P6 (13. Juli 2022)

Der Patch 9.10.1 P6 steht jetzt für Cloud Volumes ONTAP in Microsoft Azure zur Verfügung, wenn Sie über einen Connector mit Version 3.9.19 oder höher verfügen. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.10.1P6["Zeigen Sie die Liste der im P6-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.10.1 P3 (15 Mai 2022)

Der 9.10.1 P3-Patch ist jetzt für Cloud Volumes ONTAP in Microsoft Azure verfügbar, wenn Sie über einen Connector mit Version 3.9.13 oder höher verfügen. BlueXP fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.10.1P3["Zeigen Sie die Liste der im P3-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== Update zur Lizenzierung (9. Februar 2022)

Wir haben für Cloud Volumes ONTAP die folgenden Marktänderungen eingeführt:

* Das Essentials-Paket und das Professional-Paket sind ab sofort auf den AWS- und Google Cloud-Marktplätzen erhältlich.
+
Dank dieser Gebührenarten können Sie stundenweise bezahlen oder einen Jahresvertrag direkt von Ihrem Cloud-Provider abschließen. Sie haben weiterhin die Möglichkeit, eine kapazitätsstarke Lizenz direkt bei NetApp zu erwerben.

+
Wenn Sie bereits über ein Abonnement auf einem Cloud Marketplace verfügen, haben Sie auch diese neuen Angebote automatisch abonniert. Sie können sich bei der Implementierung einer neuen Cloud Volumes ONTAP Arbeitsumgebung nach Kapazitätsgebühren entscheiden.

+
Wenn Sie ein neuer Kunde sind, werden Sie von BlueXP aufgefordert, sich anzumelden, wenn Sie eine neue Arbeitsumgebung erstellen.

* Eine Lizenzierung per Node über den AWS und Google Cloud Marketplace ist veraltet und für neue Abonnenten nicht mehr verfügbar. Dazu zählen Jahresverträge und stündliche Abonnements (Explore, Standard und Premium).
+
Diese Lademethode ist weiterhin für bestehende Kunden verfügbar, die über ein aktives Abonnement verfügen.



link:concept-licensing.html["Informieren Sie sich über die Lizenzierungsoptionen für Cloud Volumes ONTAP"].



== 9.10.1 GA (31. Januar 2022)

Das Release von Cloud Volumes ONTAP 9.10.1 (General Availability, GA) ist jetzt verfügbar. Die GA-Version enthält Bug Fixes.

BlueXP fordert Sie auf, vorhandene Systeme mit einer der folgenden Versionen zu aktualisieren: 9.10.1 RC1, 9.10.0 oder 9.9.1.



== Unterstützung für mehr VM-Typen (2. Januar 2021)

Im Rahmen der BlueXP 3.9.14 Version wird Cloud Volumes ONTAP ab Version 9.10.1 mit den folgenden VM-Typen in Microsoft Azure unterstützt:

* E4ds_v4
* E8ds_v4
* E32ds_v4
* E48ds_v4


Wechseln Sie zum link:reference-configs-azure.html["Seite mit unterstützten Konfigurationen"] Entnehmen.



== 9.10.1 RC1 (28. November 2021)

Cloud Volumes ONTAP 9.10.1 Release Candidate 1 ist jetzt in AWS, Azure und Google Cloud verfügbar. Diese Version umfasst die folgenden neuen Funktionen und Verbesserungen.



=== HA-Verbesserungen in Microsoft Azure

* Wir haben die ungeplante Failover-Zeit für Cloud Volumes ONTAP HA-Paare, die in Microsoft Azure ausgeführt werden, reduziert.
* NFSv4 wird jetzt unterstützt.


Um diese Verbesserungen für Cloud Volumes ONTAP verfügbar zu machen, müssen Sie eine Funktion in Ihrem Azure Abonnement aktivieren. Ein Azure-Benutzer mit „Owner“-Berechtigungen kann die Funktion über die Azure-CLI aktivieren:

[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
BlueXP fordert Sie in einer Meldung Aktion erforderlich für Cloud Volumes ONTAP 9.10.1-Systeme auf, bei der die Funktion auf einem Azure-Abonnement aktiviert werden muss.

Beachten Sie Folgendes:

* Es gibt keine Probleme mit der Hochverfügbarkeit Ihres Cloud Volumes ONTAP HA-Paars. Diese Azure Funktion arbeitet in Kombination mit ONTAP, um die von Clients beobachteten Applikationsausfallzeiten für NFS-Protokolle zu reduzieren, die aus ungeplanten Failover-Ereignissen resultieren.
* Wenn Sie diese Funktion aktivieren, wird für Cloud Volumes ONTAP HA-Paare keine Unterbrechung verursacht.
* Wenn Sie diese Funktion auf Ihrem Azure-Abonnement aktivieren, treten keine Probleme bei anderen VMs auf.




=== Verbesserte Sicherheit

Wir haben die Sicherheit bei der Erstellung von ONTAP Images und die Sicherheit der Boot-Festplatte von Cloud Volumes ONTAP verbessert.



=== Support für Keystone Flex-Abonnements

Als Teil der Version Connector 3.9.13 können Sie jetzt ein Keystone Flex Abonnement mit Cloud Volumes ONTAP HA-Paaren verwenden. Bei dem Keystone Flex Subscription handelt es sich um einen auf Pay-as-you-grow-basierten Service auf Abonnementbasis, der ein nahtloses Hybrid-Cloud-Erlebnis für Kunden bietet, die Betriebskosten über Investitionskosten oder Leasing hinweg bevorzugen.

Ein Keystone Flex Subscription wird mit allen neuen Versionen von Cloud Volumes ONTAP unterstützt, die Sie über BlueXP implementieren können.



=== Verschlüsselungs-Management

Die Version ONTAP 9.10.1 enthält eine Erweiterung, mit der Sie Azure Key Vault (AKV) oder den Google Cloud Key Management Service zum Schutz der ONTAP-Verschlüsselungsschlüssel verwenden können.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-security.html["Weitere Informationen zur Verschlüsselungsunterstützung für Cloud Volumes ONTAP"^].



== Erforderliche Version des BlueXP Connectors

Der BlueXP-Connector muss Version 3.9.13 oder höher ausführen, um neue Cloud Volumes ONTAP 9.10.1-Systeme bereitzustellen und bestehende Systeme auf 9.10.1 zu aktualisieren.


TIP: Automatische Upgrades des Connectors sind standardmäßig aktiviert, sodass Sie die neueste Version verwenden sollten.



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von BlueXP abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.10.0 und Version 9.9.1 auf Cloud Volumes ONTAP 9.10.1 durchführen. Unter BlueXP werden Sie aufgefordert, qualifizierte Cloud Volumes ONTAP-Systeme auf Version 9.10.1 zu aktualisieren.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie aktualisiert werden können, wenn Sie von BlueXP benachrichtigt werden"^].

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.
* In AWS werden die EC2-Instanztypen c4, m4 und R4 von neuen Cloud Volumes ONTAP-Implementierungen nicht mehr unterstützt. Wenn Sie ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 zu einem Instanztyp wechseln. Wenn Sie den Instanztyp nicht ändern können, müssen Sie vor dem Upgrade die erweiterte Netzwerkumgebung aktivieren.
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Erfahren Sie, wie Sie ein Upgrade in AWS mit EC2-Instanztypen c4, m4 und R4 durchführen"^].
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

+
Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.





=== DS3_v2

Ab der Version 9.9.1 wird der DS3_v2 VM-Typ nicht mehr mit neuen und vorhandenen Cloud Volumes ONTAP-Systemen unterstützt. Wenn auf diesem VM-Typ bereits ein System ausgeführt wird, müssen Sie die VM-Typen ändern, bevor Sie auf 9.10.1 aktualisieren.
